name: pizza_repository
description: "The repo that handles pizza"
publish_to:
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  rxdart: ^0.27.7
  uuid: ^4.4.0
  image_picker: ^1.0.4
  firebase_storage: ^11.6.0

flutter:
  uses-material-design: true
